-- Migration 002: Create the submissions table
-- This stores every inventor self-assessment form submission.
-- Each row represents one complete assessment (contact info + TRL/MRL/CRL scores).

CREATE TABLE IF NOT EXISTS submissions (
  -- Primary key: UUID generated by the database
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Timestamps
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- ── Contact information ──────────────────────────────────────────────────
  full_name        VARCHAR(200) NOT NULL,
  phone            VARCHAR(30)  NOT NULL,
  affiliation      VARCHAR(300) NOT NULL,     -- university / company / research centre

  -- ── Invention information ────────────────────────────────────────────────
  invention_title  VARCHAR(500) NOT NULL,
  description      TEXT,                      -- optional, max 300 chars enforced at API layer

  -- ── Classification ───────────────────────────────────────────────────────
  sector           VARCHAR(50)  NOT NULL
                     CHECK (sector IN (
                       'agriculture', 'health', 'energy', 'ict',
                       'manufacturing', 'defense', 'environment', 'other'
                     )),
  sector_other     VARCHAR(300),              -- free-text when sector = 'other'

  -- ── Readiness levels (self-assessed) ─────────────────────────────────────
  trl              SMALLINT     NOT NULL CHECK (trl BETWEEN 1 AND 9),   -- Technology Readiness Level
  mrl              SMALLINT     NOT NULL CHECK (mrl BETWEEN 1 AND 10),  -- Manufacturing Readiness Level
  crl              SMALLINT     NOT NULL CHECK (crl BETWEEN 1 AND 9),   -- Commercialisation Readiness Level

  -- ── Meta ─────────────────────────────────────────────────────────────────
  language         CHAR(2)      NOT NULL DEFAULT 'ar'
                     CHECK (language IN ('ar', 'en')),
  declaration      BOOLEAN      NOT NULL DEFAULT TRUE,                  -- inventor accepted terms
  status           VARCHAR(20)  NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending', 'reviewed', 'accepted', 'rejected')),
  admin_notes      TEXT                                                  -- internal notes by admin
);

-- Automatically keep updated_at in sync
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_submissions_updated_at
  BEFORE UPDATE ON submissions
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();
