-- seed.sql — Initial admin account
-- ─────────────────────────────────────────────────────────────────────────────
-- ⚠️  DO NOT run this file directly in production SQL editor.
-- Instead, run the Node.js seed script which hashes the password properly:
--
--     cd nctc-assessment
--     ADMIN_USERNAME=admin ADMIN_PASSWORD=YourStrongPassword123! node server/src/db/seed.js
--
-- The seed script connects to the database using your .env credentials,
-- creates the schema (if not already done), and inserts the hashed admin user.
-- ─────────────────────────────────────────────────────────────────────────────
-- If you MUST seed via SQL (e.g., in Supabase SQL editor), replace the
-- placeholder hash below with one generated by running:
--
--     node -e "const b=require('bcryptjs'); b.hash('YourStrongPassword123!',12).then(console.log)"
--
-- Then paste the output hash into this INSERT statement.

INSERT INTO admins (username, password_hash)
VALUES (
  'admin',
  'REPLACE_WITH_BCRYPT_HASH'   -- ← replace this before running
)
ON CONFLICT (username) DO NOTHING;
